import Theming from "@/Theme/Themeing";
import "./globals.css";
import Header from "./header/Page";
import Footer from "./footer/Page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Theming>
          <Header />
          {children}
          <Footer />
        </Theming>
      </body>
    </html>
  );
}
